version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.6.10"
    ports:
     - "5672:5672"

  mongodb:
    image: "mongo:3.4"
    ports:
     - "27017:27017"

  redis:
    image: "redis:3.2.10"
    ports:
     - "6379:6379"

  python-web1:
      build: .
      ports:
       - "8081:8080"
#      volumes:
#        - /home/ionescu/projects/python/multisensorsplatform:/root/multisensorsplatform
#        - /var/log:/var/log
      depends_on:
        - rabbitmq
        - mongodb
        - redis
      tty: true
