version: '3'

services:
  python-web1:
      build: .
      ports:
       - "8081:8080"
      volumes:
        - /home/cosmin/workspace/python/multisensorsplatform/backend:/root/multisensorsplatform
        - /var/log:/var/log
      depends_on:
        - rabbitmq
        - mongodb
        - redis

  python-store-data1:
      build: .
      entrypoint: python3 ./multisensorsplatform/consummer.py --task store_data
      volumes:
        - /home/cosmin/workspace/python/multisensorsplatform/backend:/root/multisensorsplatform
        - /var/log:/var/log
      depends_on:
        - rabbitmq
        - mongodb
        - redis

  python-rules_evaluator1:
      build: .
      entrypoint: python3 ./multisensorsplatform/consummer.py --task rules_evaluator
      volumes:
        - /home/cosmin/workspace/python/multisensorsplatform/backend:/root/multisensorsplatform
        - /var/log:/var/log
      depends_on:
        - rabbitmq
        - mongodb
        - redis